version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app 
    command: sh -c "cd react-sample && npm start"
    ports:
      - "3000:3000"
    stdin_open: true 
