version: '3.9'
services:
  react-app:
    container_name: frontend-react-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app 
    command: sh -c "npm i && npm start"
    ports:
      - "3000:3000"
    stdin_open: true 
    tty: true
 