version: "3.8"

services:
    go:
      container_name: backend-go-app
      build: 
        context: .
        dockerfile : ./Dockerfile
      ports:
        - 8080:8080
      volumes:
        - .:/app/