version: "3.8"

services:
    #バックエンドを処理するgoアプリ
    go-app:
      container_name: backend-go-app
      build: 
        context: .
        dockerfile : ./Dockerfile
      #環境変数
      env_file:
       - ./.env
      environment:
        - GO_PORT
      stdin_open: true
      tty: true
      ports:
        - ${GO_PORT}:${GO_PORT}
      volumes:
        - .:/app/
    
    db:
      image: mysql:8.0
      container_name: backend-db-mysql
      env_file:
       - ./.env
      environment:
        #スーパーユーザであるrootアカウントに設定するパスワード
        MYSQL_ROOT_PASSWORD: root
        #image起動時に作成するデータベースの名前
        MYSQL_DATABASE: question_thread_db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        TZ: Asia/Tokyo
      restart: always
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      #手元のOSのディレクトリをコンテナの中のディレクトリにマウントする
      #{手元のOS側のファイルのパス}:{コンテナ内のマウント先のパス}
      volumes:
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - ${DB_PORT}:${DB_PORT}
      
    redis:
      image: "redis:latest"
      container_name: backend-redis
      env_file:
       - ./.env
      ports:
        - ${REDIS_PORT}:${REDIS_PORT}
    

